//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvSU.GAD.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string DocumentFile { get; set; }
        public string DocumentMimeType { get; set; }
        public string DocumentName { get; set; }
        public int CreatedBy { get; set; }
        public string Status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
